const product1 = '/assets/product-1.jpg';
const product2 = '/assets/product-2.jpg';
const product3 = '/assets/product-3.jpg';
const product4 = '/assets/product-4.jpg';
const product5 = '/assets/product-5.jpg';
const product6 = '/assets/product-6.jpg';
const product7 = '/assets/product-7.jpg';
const product8 = '/assets/product-8.jpg';
const product9 = '/assets/product-9.jpg';
const product10 = '/assets/product-10.jpg';
const product11 = '/assets/product-11.jpg';
const product12 = '/assets/product-12.jpg';
const product13 = '/assets/product-13.jpg';
const product14 = '/assets/product-14.jpg';
const product15 = '/assets/product-15.jpg';
const product16 = '/assets/product-16.jpg';
const product17 = '/assets/product-17.jpg';
const product18 = '/assets/product-18.jpg';
const product19 = '/assets/product-19.jpg';
const product20 = '/assets/product-20.jpg';
const product21 = '/assets/product-21.jpg';
const product22 = '/assets/product-22.jpg';
const product23 = '/assets/product-23.jpg';
const product24 = '/assets/product-24.jpg';
const product25 = '/assets/product-25.jpg';


export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  subcategory: string;
  sizes: string[];
  colors: string[];
  inStock: boolean;
  isNew?: boolean;
  isFeatured?: boolean;
  description: string;
  rating: number;
  reviewCount: number;
}

export const products: Product[] = [
  // ── Ladies (12 products) ──
  {
    id: "1",
    name: "Noir Embroidered Kurta",
    price: 8500,
    originalPrice: 10500,
    image: product1,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    description: "Exquisitely crafted black kurta with intricate gold threadwork embroidery. Perfect for formal occasions and festive gatherings.",
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: "2",
    name: "Ivory Gold Anarkali",
    price: 7200,
    image: product2,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Cream"],
    inStock: true,
    isFeatured: true,
    description: "Elegant ivory anarkali with golden embroidery details. A timeless piece that blends tradition with modern sophistication.",
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: "3",
    name: "Maroon Festive Suit",
    price: 9800,
    originalPrice: 12000,
    image: product3,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L"],
    colors: ["Maroon", "Red"],
    inStock: true,
    isNew: true,
    description: "Rich maroon suit with matching dupatta, adorned with gold embroidery. Ideal for weddings and celebrations.",
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: "6",
    name: "Royal Blue Kurta",
    price: 7800,
    image: product6,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Royal Blue"],
    inStock: true,
    isFeatured: true,
    description: "Stunning royal blue kurta with silver and gold embroidery. A majestic piece for the modern woman.",
    rating: 4.8,
    reviewCount: 27,
  },
  {
    id: "7",
    name: "Emerald Embroidered Kurta",
    price: 8900,
    originalPrice: 11000,
    image: product7,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald", "Forest Green"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    description: "Deep green kurta with traditional floral embroidery. A stunning piece that celebrates heritage craftsmanship.",
    rating: 4.9,
    reviewCount: 35,
  },
  {
    id: "8",
    name: "Rose Chiffon Dupatta",
    price: 2800,
    image: product8,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["Standard"],
    colors: ["Pink", "Rose"],
    inStock: true,
    description: "Delicate pink chiffon dupatta with gold border embroidery. The perfect finishing touch for any outfit.",
    rating: 4.6,
    reviewCount: 19,
  },
  {
    id: "9",
    name: "Pearl White Formal Dress",
    price: 12500,
    originalPrice: 15000,
    image: product9,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Pearl"],
    inStock: true,
    isFeatured: true,
    description: "Exquisite pearl white dress with intricate gold embroidery from neckline to hem. A showstopper for grand occasions.",
    rating: 5.0,
    reviewCount: 41,
  },
  {
    id: "10",
    name: "Burgundy Velvet Kurta",
    price: 10200,
    originalPrice: 13500,
    image: product10,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Burgundy", "Wine"],
    inStock: true,
    isNew: true,
    description: "Luxurious burgundy velvet kurta with silver threadwork. Perfect for winter festivities and formal events.",
    rating: 4.8,
    reviewCount: 22,
  },
  {
    id: "11",
    name: "Sky Blue Lawn Suit",
    price: 5800,
    image: product11,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sky Blue", "Powder Blue"],
    inStock: true,
    description: "Breezy pastel blue lawn suit with subtle embroidery. Ideal for everyday elegance and casual gatherings.",
    rating: 4.5,
    reviewCount: 33,
  },
  {
    id: "12",
    name: "Peach Gold Sharara",
    price: 11800,
    originalPrice: 14500,
    image: product12,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L"],
    colors: ["Peach", "Coral"],
    inStock: true,
    isFeatured: true,
    description: "Gorgeous peach sharara set with lavish gold embroidery. A statement piece for weddings and special celebrations.",
    rating: 4.9,
    reviewCount: 28,
  },
  {
    id: "13",
    name: "Teal Silk Kurta",
    price: 7500,
    image: product13,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal", "Turquoise"],
    inStock: true,
    description: "Vibrant teal silk kurta with gold embroidery accents. A refreshing choice for daytime events.",
    rating: 4.7,
    reviewCount: 16,
  },
  {
    id: "14",
    name: "Lavender Dream Dress",
    price: 9200,
    originalPrice: 11500,
    image: product14,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L"],
    colors: ["Lavender", "Lilac"],
    inStock: true,
    isNew: true,
    description: "Ethereal lavender dress with tone-on-tone embroidery. A dreamy piece that exudes grace and femininity.",
    rating: 4.8,
    reviewCount: 20,
  },
  {
    id: "24",
    name: "Coral Formal Sherwani",
    price: 13500,
    originalPrice: 16000,
    image: product24,
    category: "Ladies",
    subcategory: "Stitched",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Coral", "Salmon"],
    inStock: true,
    isNew: true,
    description: "Striking coral formal suit with elaborate gold embroidery and matching dupatta. Perfect for mehndi and festive events.",
    rating: 4.7,
    reviewCount: 14,
  },

  // ── Kids (7 products) ──
  {
    id: "4",
    name: "Princess Party Frock",
    price: 3500,
    image: product4,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    colors: ["Pink", "Peach"],
    inStock: true,
    isFeatured: true,
    description: "Adorable pink party frock with golden embroidery details. Perfect for your little princess's special occasions.",
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: "15",
    name: "Sunflower Summer Dress",
    price: 2800,
    image: product15,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["1-2Y", "2-3Y", "3-4Y", "4-5Y"],
    colors: ["Yellow", "Sunshine"],
    inStock: true,
    isNew: true,
    description: "Cheerful yellow dress with sunflower print. A delightful pick for sunny outings and playdates.",
    rating: 4.8,
    reviewCount: 29,
  },
  {
    id: "16",
    name: "Ruby Red Party Dress",
    price: 4200,
    originalPrice: 5000,
    image: product16,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["3-4Y", "4-5Y", "5-6Y", "6-7Y"],
    colors: ["Red", "Crimson"],
    inStock: true,
    isFeatured: true,
    description: "Stunning red tulle party dress with flutter sleeves and embroidered lace overlay. A showstopper for every event.",
    rating: 4.9,
    reviewCount: 37,
  },
  {
    id: "17",
    name: "Ivory Lace Dress",
    price: 3800,
    image: product17,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    colors: ["White", "Ivory"],
    inStock: true,
    description: "Classic ivory lace dress with bow detail. Timeless elegance for flower girls and formal occasions.",
    rating: 4.7,
    reviewCount: 25,
  },
  {
    id: "18",
    name: "Navy Embroidered Kurta",
    price: 3200,
    originalPrice: 4000,
    image: product18,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy", "Dark Blue"],
    inStock: true,
    isNew: true,
    description: "Elegant navy blue kurta with gold embroidery motifs. Traditional charm for your little one's festive wardrobe.",
    rating: 4.6,
    reviewCount: 21,
  },
  {
    id: "25",
    name: "Mint Bow Frock",
    price: 3000,
    image: product25,
    category: "Kids",
    subcategory: "Girls",
    sizes: ["1-2Y", "2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    colors: ["Mint", "Seafoam"],
    inStock: true,
    isFeatured: true,
    description: "Adorable mint green frock with bow detail and ruffled sleeves. A fresh and playful choice for any occasion.",
    rating: 4.8,
    reviewCount: 33,
  },

  // ── Baby Products (7 products) ──
  {
    id: "5",
    name: "Premium Baby Pillow",
    price: 1800,
    image: product5,
    category: "Baby Products",
    subcategory: "Baby Pillows",
    sizes: ["Standard"],
    colors: ["Gold", "Cream"],
    inStock: true,
    isNew: true,
    description: "Ultra-soft premium baby pillow in luxurious gold satin. Designed for comfort and elegance in your nursery.",
    rating: 4.6,
    reviewCount: 15,
  },
  {
    id: "19",
    name: "Cloud White Cot Set",
    price: 5500,
    originalPrice: 6800,
    image: product19,
    category: "Baby Products",
    subcategory: "Baby Cot Sets",
    sizes: ["Standard"],
    colors: ["White", "Cream"],
    inStock: true,
    isFeatured: true,
    description: "Complete white baby cot bedding set including comforter, sheets, and pillow. Pure cotton for your baby's comfort.",
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: "20",
    name: "Sky Blue Blanket Set",
    price: 3200,
    image: product20,
    category: "Baby Products",
    subcategory: "Baby Cot Sets",
    sizes: ["Standard"],
    colors: ["Blue", "Sky Blue"],
    inStock: true,
    isNew: true,
    description: "Soft sky blue blanket and pillow set. Premium cotton blend for maximum comfort and warmth.",
    rating: 4.7,
    reviewCount: 26,
  },
  {
    id: "21",
    name: "Mint Dream Pillow",
    price: 1500,
    image: product21,
    category: "Baby Products",
    subcategory: "Baby Pillows",
    sizes: ["Standard"],
    colors: ["Mint", "Green"],
    inStock: true,
    description: "Gentle mint green baby pillow with hypoallergenic filling. Designed for newborns and toddlers.",
    rating: 4.5,
    reviewCount: 19,
  },
  {
    id: "22",
    name: "Rose Gold Crib",
    price: 18500,
    originalPrice: 22000,
    image: product22,
    category: "Baby Products",
    subcategory: "Baby Cot Sets",
    sizes: ["Standard"],
    colors: ["Rose Gold", "Pink"],
    inStock: true,
    isFeatured: true,
    description: "Elegant rose gold baby crib with premium mattress. A statement piece for the modern nursery.",
    rating: 4.9,
    reviewCount: 12,
  },
  {
    id: "23",
    name: "Sunshine Neck Pillow",
    price: 1200,
    image: product23,
    category: "Baby Products",
    subcategory: "Baby Pillows",
    sizes: ["Standard"],
    colors: ["Yellow", "Sunshine"],
    inStock: true,
    isNew: true,
    description: "Cheerful yellow baby neck support pillow. Perfect for car seats and strollers.",
    rating: 4.4,
    reviewCount: 22,
  },
];

export const categories = [
  { name: "Ladies", subcategories: [{ name: "Stitched", active: true }, { name: "Unstitched", active: false }] },
  { name: "Gents", subcategories: [{ name: "Coming Soon", active: false }] },
  { name: "Kids", subcategories: [{ name: "Girls", active: true }, { name: "Boys", active: false }] },
  { name: "Baby Products", subcategories: [{ name: "Baby Cot Sets", active: true }, { name: "Baby Pillows", active: true }] },
];

export function formatPrice(price: number): string {
  return `Rs. ${price.toLocaleString()}`;
}